Repository brain-tec/product-variant, pull requests merged in 2024-05, with the labels that each got.

#325 Syncing from upstream OCA/product-variant (14.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
Labels: 14.0

#326 Syncing from upstream OCA/product-variant (15.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 15.0

#327 Syncing from upstream OCA/product-variant (16.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 16.0

#328 Syncing from upstream OCA/product-variant (17.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
Labels: 17.0

#329 [MIG] Make product variant form view look prettier.
  product_variant_configurator/models/pricelist.py
  product_variant_configurator/views/inherited_product_product_views.xml
Labels: enhancement, 17.0, 17.0.project_tr_736

#330 Syncing from upstream OCA/product-variant (10.0)
  purchase_order_variant_mgmt/i18n/it.po
  sale_order_variant_mgmt/i18n/it.po
  stock_picking_variant_mgmt/i18n/it.po
Labels: 10.0

#331 Syncing from upstream OCA/product-variant (11.0)
  purchase_order_variant_mgmt/i18n/it.po
  sale_order_variant_mgmt/i18n/it.po
Labels: 11.0

#332 Syncing from upstream OCA/product-variant (12.0)
  purchase_order_variant_mgmt/i18n/it.po
  sale_order_variant_mgmt/i18n/it.po
Labels: 12.0

#333 Syncing from upstream OCA/product-variant (16.0)
  README.md
  product_variant_attribute_tax/README.rst
  product_variant_attribute_tax/__manifest__.py
  product_variant_attribute_tax/static/description/index.html
  product_variant_configurator/README.rst
  product_variant_configurator/__manifest__.py
  product_variant_configurator/static/description/index.html
Labels: 16.0

#334 Syncing from upstream OCA/product-variant (16.0)
  product_variant_configurator/i18n/pt_BR.po
  product_variant_sale_price/i18n/pt_BR.po
  purchase_variant_configurator/i18n/pt_BR.po
  sale_order_line_variant_description/i18n/pt_BR.po
Labels: 16.0

#335 Syncing from upstream OCA/product-variant (16.0)
  README.md
  product_variant_configurator/README.rst
  product_variant_configurator/__manifest__.py
  product_variant_configurator/models/product_configurator.py
  product_variant_configurator/static/description/index.html
Labels: 16.0
